---
- src: geerlingguy.java
- src: geerlingguy.nginx
- src: geerlingguy.elasticsearch
  version: 2.1.1
- src: geerlingguy.elasticsearch-curator
  version: 1.0.7
- src: geerlingguy.kibana
  version: 1.0.8
- src: geerlingguy.logstash
  version: 2.0.0
- src: geerlingguy.logstash-forwarder
  version: 1.0.3
