# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # ELK server.
  config.vm.define "logs" do |logs|
    logs.vm.hostname = "logs"
    logs.vm.network :private_network, ip: "192.168.9.90"

    logs.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/elk/playbook.yml"
      ansible.inventory_path = "provisioning/elk/inventory"
      ansible.sudo = true
    end
  end

  # Web server.
  config.vm.define "webs" do |webs|
    webs.vm.hostname = "webs"
    webs.vm.network :private_network, ip: "192.168.9.91"

    webs.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/web/playbook.yml"
      ansible.inventory_path = "provisioning/web/inventory"
      ansible.sudo = true
    end
  end

end
