# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos64"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--name", "svn2git"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "svn2git"
  config.vm.network :private_network, ip: "192.168.30.30"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :svn2git do |svn2git|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.sudo = true
  end

end
